### ISSUE TITLE
Parsing is not working anymore

### ISSUE THREAD

**Issue by shellshock1953** [vgavro/my-kyivstar#1]
Seems parsing is not working
```trace
Traceback (most recent call last):
  File "~/bin/my-kyivstar", line 8, in <module>
    sys.exit(main())
  File "~/lib/python3.9/site-packages/my_kyivstar.py", line 91, in main
    session.login()
  File "~/lib/python3.9/site-packages/my_kyivstar.py", line 34, in login
    bc = re.search('bc=\'([\w\d]+)\'', resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by vgavro** [comment]
Fixed with https://github.com/vgavro/my-kyivstar/commit/955fa99cdb3b478002f6261b29a550208ce7f42e

uploaded new version (0.0.3) to pypi
